In [17]:
import pandas as pd
shol_shot = pd.read_csv("school_shooting.csv")
shol_shot['Date'] = pd.to_datetime(shol_shot['Date'])
shol_shot['State'] = shol_shot['State'].str.strip()
shol_shot['Location'] = shol_shot['Location'].str.strip()
shol_shot['School Name'] = shol_shot['School Name'].str.strip()
shol_shot['School Name'].nunique()

297

In [20]:
testing_dup = shol_shot.groupby('School Name').agg({'School Name': "count"})
mask = testing_dup['School Name'] == 2
testing_dup[mask]

# as a filter to clean redendent data

                                           School Name
School Name
Apostolic Revival Center Christian School            2
Benjamin Banneker High School                        2
Cesar Chavez High School                             2
Charles F. Brush High School                         2
Delaware State University                            2
Elizabeth City State University                      2
Huffman High School                                  2
Indiana State University                             2
Johnson C. Smith University                          2
Kansas State University                              2
Lane College                                         2
Langston University                                  2
Paine College                                        2
University of Missouri                               2
University of Utah                                   2
Virginia State University                            2

In [30]:
## Data Ready and exploration:

shol_shot = pd.read_csv("school_shooting.csv")
shol_shot['Date'] = pd.to_datetime(shol_shot['Date'])
shol_shot['State'] = shol_shot['State'].str.strip()
shol_shot['Location'] = shol_shot['Location'].str.strip()
shol_shot['School Name'] = shol_shot['School Name'].str.strip()

In [31]:
shol_shot.groupby('School Type').agg({'School Type': "count"})

                       School Type
School Type
College or University          124
Community College                7
Elementary School               40
High School                    128
K-12 School                      5
Middle School                   25
Preschool                        6

In [8]:
import pandas as pd
df = pd.read_csv("school_shooting.csv")
df['Date'] = pd.to_datetime(df['Date'])
df.head()
#df.tail()

,Date,Death,Injuries,Location,State,School Name,School Type
0,2013-01-07,1.0,0.0,Fort Myers,FL,Apostolic Revival Center Christian School,Preschool
1,2013-01-10,0.0,2.0,Taft,CA,Taft Union High School,High School
2,2013-01-12,0.0,1.0,Detroit,MI,Osborn High School,High School
3,2013-01-15,0.0,2.0,St. Louis,MO,Stevens Institute of Business & Arts,College or University
4,2013-01-15,3.0,0.0,Hazard,KY,Hazard Community and Technical College,College or University

## get data into MongoDB

### get data into dictionary

In [23]:
import pymongo
from bs4 import BeautifulSoup 
import pymongo 
from pprint import pprint 
import pandas as pd
import requests
from splinter import Browser
import json
import tweepy
import os
import time

In [13]:
column_names = list(df.columns)

In [14]:
final_list = []
name_list = []
for item in column_names:
    name_list.append(item)
    final_list.append([i for i in df[item]])

In [18]:

dictionary = dict(zip(name_list, final_list))
print(dictionary)
dictionary['Date']

{'Date': [Timestamp('2013-01-07 00:00:00'), Timestamp('2013-01-10 00:00:00'), Timestamp('2013-01-12 00:00:00'), Timestamp('2013-01-15 00:00:00'), Timestamp('2013-01-15 00:00:00'), Timestamp('2013-01-16 00:00:00'), Timestamp('2013-01-22 00:00:00'), Timestamp('2013-01-31 00:00:00'), Timestamp('2013-01-31 00:00:00'), Timestamp('2013-03-18 00:00:00'), Timestamp('2013-04-12 00:00:00'), Timestamp('2013-04-16 00:00:00'), Timestamp('2013-04-18 00:00:00'), Timestamp('2013-05-14 00:00:00'), Timestamp('2013-06-07 00:00:00'), Timestamp('2013-08-20 00:00:00'), Timestamp('2013-08-23 00:00:00'), Timestamp('2013-08-30 00:00:00'), Timestamp('2013-10-04 00:00:00'), Timestamp('2013-10-21 00:00:00'), Timestamp('2013-11-02 00:00:00'), Timestamp('2013-11-03 00:00:00'), Timestamp('2013-11-13 00:00:00'), Timestamp('2013-12-04 00:00:00'), Timestamp('2013-12-13 00:00:00'), Timestamp('2013-12-19 00:00:00'), Timestamp('2014-01-09 00:00:00'), Timestamp('2014-01-13 00:00:00'), Timestamp('2014-01-14 00:00:00'), Timestamp('2014-01-17 00:00:00'), Timestamp('2014-01-20 00:00:00'), Timestamp('2014-01-21 00:00:00'), Timestamp('2014-01-24 00:00:00'), Timestamp('2014-01-25 00:00:00'), Timestamp('2014-01-27 00:00:00'), Timestamp('2014-01-28 00:00:00'), Timestamp('2014-01-28 00:00:00'), Timestamp('2014-01-30 00:00:00'), Timestamp('2014-01-31 00:00:00'), Timestamp('2014-01-31 00:00:00'), Timestamp('2014-02-10 00:00:00'), Timestamp('2014-02-10 00:00:00'), Timestamp('2014-02-12 00:00:00'), Timestamp('2014-02-22 00:00:00'), Timestamp('2014-03-12 00:00:00'), Timestamp('2014-04-09 00:00:00'), Timestamp('2014-04-11 00:00:00'), Timestamp('2014-05-04 00:00:00'), Timestamp('2014-05-08 00:00:00'), Timestamp('2014-05-08 00:00:00'), Timestamp('2014-05-14 00:00:00'), Timestamp('2014-06-05 00:00:00'), Timestamp('2014-06-10 00:00:00'), Timestamp('2014-09-09 00:00:00'), Timestamp('2014-09-11 00:00:00'), Timestamp('2014-09-27 00:00:00'), Timestamp('2014-09-30 00:00:00'), Timestamp('2014-09-30 00:00:00'), Timestamp('2014-10-03 00:00:00'), Timestamp('2014-10-24 00:00:00'), Timestamp('2014-11-20 00:00:00'), Timestamp('2014-11-20 00:00:00'), Timestamp('2014-12-05 00:00:00'), Timestamp('2014-12-12 00:00:00'), Timestamp('2015-01-15 00:00:00'), Timestamp('2015-01-16 00:00:00'), Timestamp('2015-02-04 00:00:00'), Timestamp('2015-02-14 00:00:00'), Timestamp('2015-02-23 00:00:00'), Timestamp('2015-03-30 00:00:00'), Timestamp('2015-04-13 00:00:00'), Timestamp('2015-04-16 00:00:00'), Timestamp('2015-04-27 00:00:00'), Timestamp('2015-05-12 00:00:00'), Timestamp('2015-05-24 00:00:00'), Timestamp('2015-08-27 00:00:00'), Timestamp('2015-09-03 00:00:00'), Timestamp('2015-09-14 00:00:00'), Timestamp('2015-09-30 00:00:00'), Timestamp('2015-10-01 00:00:00'), Timestamp('2015-10-09 00:00:00'), Timestamp('2015-10-09 00:00:00'), Timestamp('2015-10-22 00:00:00'), Timestamp('2015-11-01 00:00:00'), Timestamp('2015-11-20 00:00:00'), Timestamp('2016-01-22 00:00:00'), Timestamp('2016-01-29 00:00:00'), Timestamp('2016-02-09 00:00:00'), Timestamp('2016-02-12 00:00:00'), Timestamp('2016-02-29 00:00:00'), Timestamp('2016-04-23 00:00:00'), Timestamp('2016-06-01 00:00:00'), Timestamp('2016-06-08 00:00:00'), Timestamp('2016-09-09 00:00:00'), Timestamp('2016-09-28 00:00:00'), Timestamp('2016-10-11 00:00:00'), Timestamp('2016-10-13 00:00:00'), Timestamp('2016-10-18 00:00:00'), Timestamp('2016-10-25 00:00:00'), Timestamp('2016-12-01 00:00:00'), Timestamp('2017-01-20 00:00:00'), Timestamp('2017-01-20 00:00:00'), Timestamp('2017-03-21 00:00:00'), Timestamp('2017-04-10 00:00:00'), Timestamp('2017-05-04 00:00:00'), Timestamp('2017-09-13 00:00:00'), Timestamp('2017-09-20 00:00:00'), Timestamp('2017-11-14 00:00:00'), Timestamp('2017-12-07 00:00:00'), Timestamp('2018-01-10 00:00:00'), Timestamp('2018-01-20 00:00:00'), Timestamp('2018-01-22 00:00:00'), Timestamp('2018-01-22 00:00:00'), Timestamp('2018-01-23 00:00:00'), Timestamp('2018-01-25 00:00:00'), Timestamp('2018-01-31 00:00:00'), Timestamp('2018-02-01 00:00:00'), Timestamp('2018-02-05 00:00:00'), Timestamp('2018-02-14 00:00:00'), Timestamp('2018-03-02 00:00:00'), Timestamp('2018-03-07 00:00:00'), Timestamp('2018-03-09 00:00:00'), Timestamp('2018-03-14 00:00:00'), Timestamp('2018-03-20 00:00:00'), Timestamp('2018-04-20 00:00:00'), Timestamp('2018-05-11 00:00:00'), Timestamp('2018-05-16 00:00:00'), Timestamp('2018-05-18 00:00:00'), Timestamp('2018-05-18 00:00:00'), Timestamp('2018-05-25 00:00:00'), Timestamp('2018-05-05 00:00:00'), Timestamp('2018-05-03 00:00:00'), Timestamp('2018-04-22 00:00:00'), Timestamp('2018-04-19 00:00:00'), Timestamp('2018-04-12 00:00:00'), Timestamp('2018-03-16 00:00:00'), Timestamp('2018-03-13 00:00:00'), Timestamp('2018-03-13 00:00:00'), Timestamp('2018-03-05 00:00:00'), Timestamp('2018-03-04 00:00:00'), Timestamp('2018-02-28 00:00:00'), Timestamp('2018-02-27 00:00:00'), Timestamp('2018-02-27 00:00:00'), Timestamp('2018-02-26 00:00:00'), Timestamp('2018-02-24 00:00:00'), Timestamp('2018-02-23 00:00:00'), Timestamp('2018-02-20 00:00:00'), Timestamp('2018-02-15 00:00:00'), Timestamp('2018-02-08 00:00:00'), Timestamp('2018-01-26 00:00:00'), Timestamp('2018-01-15 00:00:00'), Timestamp('2018-01-04 00:00:00'), Timestamp('2017-12-31 00:00:00'), Timestamp('2017-12-27 00:00:00'), Timestamp('2017-12-19 00:00:00'), Timestamp('2017-12-14 00:00:00'), Timestamp('2017-12-13 00:00:00'), Timestamp('2017-12-12 00:00:00'), Timestamp('2017-12-12 00:00:00'), Timestamp('2017-12-11 00:00:00'), Timestamp('2017-11-30 00:00:00'), Timestamp('2017-11-29 00:00:00'), Timestamp('2017-11-28 00:00:00'), Timestamp('2017-11-23 00:00:00'), Timestamp('2017-11-17 00:00:00'), Timestamp('2017-11-11 00:00:00'), Timestamp('2017-11-10 00:00:00'), Timestamp('2017-11-10 00:00:00'), Timestamp('2017-11-09 00:00:00'), Timestamp('2017-11-07 00:00:00'), Timestamp('2017-11-03 00:00:00'), Timestamp('2017-10-31 00:00:00'), Timestamp('2017-10-25 00:00:00'), Timestamp('2017-10-19 00:00:00'), Timestamp('2017-10-14 00:00:00'), Timestamp('2017-10-11 00:00:00'), Timestamp('2017-10-09 00:00:00'), Timestamp('2017-09-30 00:00:00'), Timestamp('2017-09-29 00:00:00'), Timestamp('2017-09-17 00:00:00'), Timestamp('2017-09-12 00:00:00'), Timestamp('2017-09-08 00:00:00'), Timestamp('2017-09-08 00:00:00'), Timestamp('2017-09-05 00:00:00'), Timestamp('2017-09-01 00:00:00'), Timestamp('2017-08-17 00:00:00'), Timestamp('2017-07-23 00:00:00'), Timestamp('2017-07-21 00:00:00'), Timestamp('2017-07-19 00:00:00'), Timestamp('2017-07-13 00:00:00'), Timestamp('2017-06-22 00:00:00'), Timestamp('2017-06-16 00:00:00'), Timestamp('2017-06-05 00:00:00'), Timestamp('2017-05-24 00:00:00'), Timestamp('2017-05-23 00:00:00'), Timestamp('2017-05-15 00:00:00'), Timestamp('2017-05-02 00:00:00'), Timestamp('2017-04-25 00:00:00'), Timestamp('2017-04-15 00:00:00'), Timestamp('2017-04-07 00:00:00'), Timestamp('2017-03-31 00:00:00'), Timestamp('2017-03-15 00:00:00'), Timestamp('2017-03-13 00:00:00'), Timestamp('2017-02-06 00:00:00'), Timestamp('2017-01-27 00:00:00'), Timestamp('2017-01-22 00:00:00'), Timestamp('2017-01-17 00:00:00'), Timestamp('2017-01-10 00:00:00'), Timestamp('2017-01-05 00:00:00'), Timestamp('2016-12-29 00:00:00'), Timestamp('2016-12-09 00:00:00'), Timestamp('2016-11-17 00:00:00'), Timestamp('2016-11-11 00:00:00'), Timestamp('2016-11-03 00:00:00'), Timestamp('2016-11-02 00:00:00'), Timestamp('2016-10-23 00:00:00'), Timestamp('2016-10-23 00:00:00'), Timestamp('2016-10-06 00:00:00'), Timestamp('2016-09-15 00:00:00'), Timestamp('2016-09-08 00:00:00'), Timestamp('2016-09-02 00:00:00'), Timestamp('2016-08-25 00:00:00'), Timestamp('2016-07-25 00:00:00'), Timestamp('2016-07-07 00:00:00'), Timestamp('2016-06-10 00:00:00'), Timestamp('2016-06-07 00:00:00'), Timestamp('2016-05-15 00:00:00'), Timestamp('2016-05-13 00:00:00'), Timestamp('2016-05-11 00:00:00'), Timestamp('2016-05-06 00:00:00'), Timestamp('2016-05-06 00:00:00'), Timestamp('2016-05-06 00:00:00'), Timestamp('2016-05-05 00:00:00'), Timestamp('2016-05-02 00:00:00'), Timestamp('2016-04-29 00:00:00'), Timestamp('2016-04-16 00:00:00'), Timestamp('2016-04-02 00:00:00'), Timestamp('2016-03-27 00:00:00'), Timestamp('2016-03-23 00:00:00'), Timestamp('2016-03-21 00:00:00'), Timestamp('2016-03-15 00:00:00'), Timestamp('2016-02-26 00:00:00'), Timestamp('2016-02-17 00:00:00'), Timestamp('2016-01-20 00:00:00'), Timestamp('2016-01-13 00:00:00'), Timestamp('2016-01-12 00:00:00'), Timestamp('2015-12-29 00:00:00'), Timestamp('2015-12-18 00:00:00'), Timestamp('2015-11-29 00:00:00'), Timestamp('2015-11-11 00:00:00'), Timestamp('2015-11-10 00:00:00'), Timestamp('2015-11-05 00:00:00'), Timestamp('2015-10-25 00:00:00'), Timestamp('2015-10-24 00:00:00'), Timestamp('2015-10-15 00:00:00'), Timestamp('2015-10-15 00:00:00'), Timestamp('2015-10-11 00:00:00'), Timestamp('2015-10-06 00:00:00'), Timestamp('2015-10-02 00:00:00'), Timestamp('2015-09-28 00:00:00'), Timestamp('2015-09-22 00:00:00'), Timestamp('2015-09-11 00:00:00'), Timestamp('2015-08-26 00:00:00'), Timestamp('2015-08-25 00:00:00'), Timestamp('2015-08-23 00:00:00'), Timestamp('2015-08-08 00:00:00'), Timestamp('2015-08-08 00:00:00'), Timestamp('2015-07-27 00:00:00'), Timestamp('2015-07-24 00:00:00'), Timestamp('2015-07-05 00:00:00'), Timestamp('2015-06-23 00:00:00'), Timestamp('2015-06-04 00:00:00'), Timestamp('2015-05-27 00:00:00'), Timestamp('2015-05-20 00:00:00'), Timestamp('2015-05-05 00:00:00'), Timestamp('2015-05-04 00:00:00'), Timestamp('2015-05-04 00:00:00'), Timestamp('2015-04-22 00:00:00'), Timestamp('2015-04-19 00:00:00'), Timestamp('2015-04-18 00:00:00'), Timestamp('2015-04-17 00:00:00'), Timestamp('2015-04-04 00:00:00'), Timestamp('2015-04-02 00:00:00'), Timestamp('2015-04-02 00:00:00'), Timestamp('2015-02-15 00:00:00'), Timestamp('2015-02-15 00:00:00'), Timestamp('2015-02-15 00:00:00'), Timestamp('2015-02-05 00:00:00'), Timestamp('2015-02-02 00:00:00'), Timestamp('2015-01-26 00:00:00'), Timestamp('2015-01-23 00:00:00'), Timestamp('2014-12-17 00:00:00'), Timestamp('2014-12-17 00:00:00'), Timestamp('2014-11-23 00:00:00'), Timestamp('2014-10-21 00:00:00'), Timestamp('2014-10-18 00:00:00'), Timestamp('2014-10-13 00:00:00'), Timestamp('2014-10-08 00:00:00'), Timestamp('2014-09-10 00:00:00'), Timestamp('2014-09-05 00:00:00'), Timestamp('2014-09-02 00:00:00'), Timestamp('2014-08-14 00:00:00'), Timestamp('2014-08-13 00:00:00'), Timestamp('2014-06-27 00:00:00'), Timestamp('2014-06-23 00:00:00'), Timestamp('2014-05-21 00:00:00'), Timestamp('2014-05-03 00:00:00'), Timestamp('2014-05-02 00:00:00'), Timestamp('2014-04-21 00:00:00'), Timestamp('2014-04-21 00:00:00'), Timestamp('2014-04-16 00:00:00'), Timestamp('2014-04-03 00:00:00'), Timestamp('2014-03-30 00:00:00'), Timestamp('2014-03-23 00:00:00'), Timestamp('2014-03-08 00:00:00'), Timestamp('2014-03-07 00:00:00'), Timestamp('2014-03-02 00:00:00'), Timestamp('2014-02-20 00:00:00'), Timestamp('2014-02-07 00:00:00'), Timestamp('2014-01-15 00:00:00'), Timestamp('2013-11-21 00:00:00'), Timestamp('2013-11-01 00:00:00'), Timestamp('2013-10-15 00:00:00'), Timestamp('2013-09-28 00:00:00'), Timestamp('2013-09-21 00:00:00'), Timestamp('2013-08-22 00:00:00'), Timestamp('2013-08-15 00:00:00'), Timestamp('2013-06-19 00:00:00'), Timestamp('2013-05-03 00:00:00'), Timestamp('2013-04-29 00:00:00'), Timestamp('2013-04-15 00:00:00'), Timestamp('2013-04-13 00:00:00'), Timestamp('2013-03-21 00:00:00'), Timestamp('2013-02-27 00:00:00'), Timestamp('2013-02-13 00:00:00'), Timestamp('2013-02-01 00:00:00'), Timestamp('2013-01-08 00:00:00')], 'Death': [1.0, 0.0, 0.0, 0.0, 3.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 6.0, 0.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 5.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2.0, 0.0, 10.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 1.0, 2.0, 1.0, 1.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 2.0, 1.0, 0.0, 6.0, 3.0, 0.0, 1.0, 0.0, 0.0, 2.0, 0.0, 1.0, 0.0, 0.0, 17.0, 2.0, 1.0, 0.0, 2.0, 2.0, 0.0, 0.0, 0.0, 10.0, 1.0, 0.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 'Injuries': [0.0, 2.0, 1.0, 2.0, 0.0, 0.0, 3.0, 0.0, 2.0, 0.0, 2.0, 3.0, 0.0, 0.0, 4.0, 0.0, 2.0, 1.0, 2.0, 2.0, 1.0, 2.0, 3.0, 1.0, 0.0, 1.0, 1.0, 1.0, 3.0, 2.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 3.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 3.0, 1.0, 0.0, 4.0, 3.0, 2.0, 2.0, 0.0, 3.0, 1.0, 0.0, 1.0, 0.0, 2.0, 7.0, 0.0, 2.0, 0.0, 1.0, 9.0, 3.0, 1.0, 3.0, 1.0, 0.0, 1.0, 0.0, 4.0, 0.0, 4.0, 2.0, 0.0, 3.0, 2.0, 2.0, 1.0, 2.0, 4.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 3.0, 1.0, 18.0, 0.0, 0.0, 0.0, 1.0, 1.0, 18.0, 0.0, 0.0, 5.0, 1.0, 17.0, 0.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 14.0, 3.0, 2.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], 'Location': ['Fort Myers', 'Taft', 'Detroit', 'St. Louis', 'Hazard', 'Chicago', 'Houston', 'Phoenix', 'Atlanta', 'Orlando', 'Christiansburg', 'Tuscaloosa', 'Cambridge', 'Birmingham', 'Santa Monica', 'Decatur', 'Sardis', 'Winston-Salem', 'Pine Hills', 'Sparks', 'Greensboro', 'Stone Mountain', 'Pittsburgh', 'Winter Garden', 'Centennial', 'Fresno', 'Jackson', 'New Haven', 'Roswell', 'Philadelphia', 'Chester', 'West Lafayette', 'Orangeburg', 'Los Angeles', 'Carbondale', 'Nashville', 'Grambling', 'Palm Bay', 'Phoenix', 'Des Moines', 'Salisbury', 'Lyndhurst', 'Los Angeles', 'Augusta', 'Miami', 'Greenville', 'Detroit', 'Augusta', 'Georgetown', 'Lawrenceville', 'Richmond', 'Seattle', 'Troutdale', 'Miami', 'Taylorsville', 'Terre Haute', 'Albermarle', 'Louisville', 'Fairburn', 'Marysville', 'Tallahasse', 'Miami', 'Claremore', 'Portland', 'Milwaukee', 'Ocala', 'Frederick', 'Merced', 'Daytona Beach', 'University City', 'Goldsboro', 'Paradis', 'Lacey', 'Tempe', 'Flint', 'Savannah', 'Sacramento', 'Cleveland', 'Harrisburg', 'Roseburg', 'Flagstaff', 'Houston', 'Nashville', 'Winston-Salem', 'North Las Vegas', 'Indianapolis', 'Philadelphia', 'Muskegon Heights High School', 'Glendale', 'Middletown', 'Antigo', 'Los Angeles', 'Dorchester', 'Alpine', 'Townville', 'Prichard', 'Columbus', 'San Francisco', 'Sandy', 'Bountiful', 'West Liberty', 'West Liberty', 'King City', 'San Bernardino', 'Irving', 'Rockford', 'Mattoon', 'Corning', 'Aztec', 'Denison', 'Winston-Salem', 'Italy', 'New Orleans', 'Benton', 'Mobile', 'Philadelphia', 'Los Angeles', 'Oxon Hill', 'Parkland', 'Mount Pleasant', 'Birmingham', 'Lexington', 'Birmingham', 'Great Mills', 'Ocala', 'Palmdale', 'Dixon', 'Santa Fe', 'Jonesboro', 'Noblesville', 'Fowlerville', 'Waynesboro', 'Atlanta', 'Jackson', 'Raytown', 'Missoula', 'Seaside', 'Alexandria', 'Cadet', 'San Marcos', 'Dalton', 'Norfolk', 'Itta Bena', 'Tacoma', 'Savannah', 'Hammond', 'Massillon', 'Coconut Creek', 'New York', 'Dearborn', 'Marshall', 'Seattle', 'Marysville', 'Lancaster', 'Beecher', 'Dallas', 'Monaca', 'East Stroudsburg', 'Pasadena', 'High Point', 'Virginia Beach', 'Lima', 'San Jose', 'Denver', 'Jackson', 'Albany', 'Milledgeville', 'Texarkana', 'Fulton County', 'Fort Worth', 'Lansing', 'Salt Lake City', 'Grambling', 'Petersburg', 'Petersburg', 'Easton', 'Lubbock', 'Commodore', "Lee's Summit", 'Akron', 'St. Paul', 'Columbus', 'North Little Rock', 'Nashville', 'College Station', 'Lithia Springs', 'Fayetteville', 'Spanish Fork', 'Milwaukee', 'Las Vegas', 'Florence', 'Chicago', 'Fort Wayne', 'Greensboro', 'Kirbyville', 'Moss Bluff', 'Irving', 'Orem', 'Tulsa', 'St. Paul', 'Pensacola', 'Gaffney', 'Wilberforce', 'Scotlandville', 'Aiken', 'Manhattan', 'Eastpoint', 'Alexander City', 'Lebanon', 'Salt Lake City', 'St. Louis', 'St. Paul', 'Auburn', 'Berthoud', 'Grand Junction', 'Huntsville', 'Caledonia', 'Fort Worth', 'Stephenville', 'Alpine', 'Tulsa', 'Booneville', 'Ava', 'Dallas', 'Vallejo', 'Columbia', 'Augusta', 'Greenville', 'Jamaica', 'Panama City', 'Columbia', 'Twin Falls', 'Beltsville', 'Dallas', 'Charleston', 'Tuskegee', 'Manhattan', 'Tacoma', 'Charlotte', 'Atlanta', 'Birmingham', 'Palestine', 'Homosassa', 'Indianapolis', 'Camden', 'Dover', 'Greeley', 'Jackson', 'Columbus', 'Sulphur Rock', 'Lecanto', 'Moultrie', 'Durham', 'San Antonio', 'Langston', 'San Antonio', 'Tampa', 'Houston', 'University City', 'Butte', 'Statesville', 'Lafayette', 'Houston', 'Augusta', 'Richmond', 'Paradise', 'Wichita', 'Gainesville', 'Converse', 'Dallas', 'Fort Calhoun', 'Franklin', 'Everglades City', 'Robinson', 'Conyers', 'Orem', 'Cleveland', 'Las Vegas', 'Charlotte', 'Dover', 'Seguin', 'Everett', 'Monaca', 'Jackson', 'Little Rock', 'Athens', 'Merced', 'Columbia', 'Mankato', 'Roseville', 'Hardeeville', 'Waterville', 'Pittsburgh', 'Annapolis', 'Memphis', 'Langston', 'Nashville', 'Elizabeth City', 'Lake Mary', 'Savannah', 'Pocatello', 'Newport News', 'Fredrick', 'Miami', 'Benton', 'Milwaukee', 'Everett', 'Milwaukee', 'Griffith', 'Provo', 'Council Bluffs', 'Kent', 'Savannah', 'Newark', 'Oshkosh', 'Tallulah', 'Westminster', 'Raytown', 'Bend', 'Lancaster', 'Rapid City', 'Algona', 'Austin', 'Gray', 'Savannah', 'Memphis', 'Clarksville', 'West Palm Beach', 'Hattiesburg', 'Cincinnati', 'Grambling', 'Elizabeth City', 'Southgate', 'Atlanta', 'San Leandro', 'Altanta', 'Fort Myers'], 'State': [' FL', ' CA', ' MI', ' MO', ' KY', ' IL', ' TX', 'AZ', ' GA', ' FL', ' VA', ' AL', 'MA', 'AL', ' CA', ' GA', ' MS', ' NC', ' FL', ' NV', ' NC', ' GA', ' PA', ' FL', ' CO', ' CA', ' TN', ' CT', ' NM', ' PA', ' PA', ' IN', ' SC', ' CA', ' IL', ' TN', ' LA', ' FL', ' AZ', ' IA', ' NC', ' OH', ' CA', ' GA', ' FL', ' NC', ' MI', ' GA', ' KY', ' GA', ' CA', ' WA', ' OR', 'FL', ' UT', ' IN', ' NC', ' KY', ' GA', ' WA', ' FL', ' FL', ' OK', ' OR', ' WI', ' FL', ' MD', ' CA', ' FL', ' MI', ' NC', ' LA', ' WA', ' AZ', ' MI', ' GA', ' CA', ' MS', ' SD', ' OR', ' AZ', ' TX', ' TN', ' NC', ' NV', ' IN', ' PA', ' MI', ' AZ', ' OH', ' WI', ' CA', ' MA', ' TX', ' SC', ' AL', ' OH', ' CA', ' UT', ' UT', ' OH', ' OH', ' CA', ' CA', ' TX', ' WA', ' IL', ' CA', ' NM', ' TX', ' NC', ' TX', ' LA', ' KY', '

[Timestamp('2013-01-07 00:00:00'),
 Timestamp('2013-01-10 00:00:00'),
 Timestamp('2013-01-12 00:00:00'),
 Timestamp('2013-01-15 00:00:00'),
 Timestamp('2013-01-15 00:00:00'),
 Timestamp('2013-01-16 00:00:00'),
 Timestamp('2013-01-22 00:00:00'),
 Timestamp('2013-01-31 00:00:00'),
 Timestamp('2013-01-31 00:00:00'),
 Timestamp('2013-03-18 00:00:00'),
 Timestamp('2013-04-12 00:00:00'),
 Timestamp('2013-04-16 00:00:00'),
 Timestamp('2013-04-18 00:00:00'),
 Timestamp('2013-05-14 00:00:00'),
 Timestamp('2013-06-07 00:00:00'),
 Timestamp('2013-08-20 00:00:00'),
 Timestamp('2013-08-23 00:00:00'),
 Timestamp('2013-08-30 00:00:00'),
 Timestamp('2013-10-04 00:00:00'),
 Timestamp('2013-10-21 00:00:00'),
 Timestamp('2013-11-02 00:00:00'),
 Timestamp('2013-11-03 00:00:00'),
 Timestamp('2013-11-13 00:00:00'),
 Timestamp('2013-12-04 00:00:00'),
 Timestamp('2013-12-13 00:00:00'),
 Timestamp('2013-12-19 00:00:00'),
 Timestamp('2014-01-09 00:00:00'),
 Timestamp('2014-01-13 00:00:00'),
 Timestamp('2014-01-14 00:00:00'),
 Timestamp('2014-01-17 00:00:00'),
 Timestamp('2014-01-20 00:00:00'),
 Timestamp('2014-01-21 00:00:00'),
 Timestamp('2014-01-24 00:00:00'),
 Timestamp('2014-01-25 00:00:00'),
 Timestamp('2014-01-27 00:00:00'),
 Timestamp('2014-01-28 00:00:00'),
 Timestamp('2014-01-28 00:00:00'),
 Timestamp('2014-01-30 00:00:00'),
 Timestamp('2014-01-31 00:00:00'),
 Timestamp('2014-01-31 00:00:00'),
 Timestamp('2014-02-10 00:00:00'),
 Timestamp('2014-02-10 00:00:00'),
 Timestamp('2014-02-12 00:00:00'),
 Timestamp('2014-02-22 00:00:00'),
 Timestamp('2014-03-12 00:00:00'),
 Timestamp('2014-04-09 00:00:00'),
 Timestamp('2014-04-11 00:00:00'),
 Timestamp('2014-05-04 00:00:00'),
 Timestamp('2014-05-08 00:00:00'),
 Timestamp('2014-05-08 00:00:00'),
 Timestamp('2014-05-14 00:00:00'),
 Timestamp('2014-06-05 00:00:00'),
 Timestamp('2014-06-10 00:00:00'),
 Timestamp('2014-09-09 00:00:00'),
 Timestamp('2014-09-11 00:00:00'),
 Timestamp('2014-09-27 00:00:00'),
 Timestamp('2014-09-30 00:00:00'),
 Timestamp('2014-09-30 00:00:00'),
 Timestamp('2014-10-03 00:00:00'),
 Timestamp('2014-10-24 00:00:00'),
 Timestamp('2014-11-20 00:00:00'),
 Timestamp('2014-11-20 00:00:00'),
 Timestamp('2014-12-05 00:00:00'),
 Timestamp('2014-12-12 00:00:00'),
 Timestamp('2015-01-15 00:00:00'),
 Timestamp('2015-01-16 00:00:00'),
 Timestamp('2015-02-04 00:00:00'),
 Timestamp('2015-02-14 00:00:00'),
 Timestamp('2015-02-23 00:00:00'),
 Timestamp('2015-03-30 00:00:00'),
 Timestamp('2015-04-13 00:00:00'),
 Timestamp('2015-04-16 00:00:00'),
 Timestamp('2015-04-27 00:00:00'),
 Timestamp('2015-05-12 00:00:00'),
 Timestamp('2015-05-24 00:00:00'),
 Timestamp('2015-08-27 00:00:00'),
 Timestamp('2015-09-03 00:00:00'),
 Timestamp('2015-09-14 00:00:00'),
 Timestamp('2015-09-30 00:00:00'),
 Timestamp('2015-10-01 00:00:00'),
 Timestamp('2015-10-09 00:00:00'),
 Timestamp('2015-10-09 00:00:00'),
 Timestamp('2015-10-22 00:00:00'),
 Timestamp('2015-11-01 00:00:00'),
 Timestamp('2015-11-20 00:00:00'),
 Timestamp('2016-01-22 00:00:00'),
 Timestamp('2016-01-29 00:00:00'),
 Timestamp('2016-02-09 00:00:00'),
 Timestamp('2016-02-12 00:00:00'),
 Timestamp('2016-02-29 00:00:00'),
 Timestamp('2016-04-23 00:00:00'),
 Timestamp('2016-06-01 00:00:00'),
 Timestamp('2016-06-08 00:00:00'),
 Timestamp('2016-09-09 00:00:00'),
 Timestamp('2016-09-28 00:00:00'),
 Timestamp('2016-10-11 00:00:00'),
 Timestamp('2016-10-13 00:00:00'),
 Timestamp('2016-10-18 00:00:00'),
 Timestamp('2016-10-25 00:00:00'),
 Timestamp('2016-12-01 00:00:00'),
 Timestamp('2017-01-20 00:00:00'),
 Timestamp('2017-01-20 00:00:00'),
 Timestamp('2017-03-21 00:00:00'),
 Timestamp('2017-04-10 00:00:00'),
 Timestamp('2017-05-04 00:00:00'),
 Timestamp('2017-09-13 00:00:00'),
 Timestamp('2017-09-20 00:00:00'),
 Timestamp('2017-11-14 00:00:00'),
 Timestamp('2017-12-07 00:00:00'),
 Timestamp('2018-01-10 00:00:00'),
 Timestamp('2018-01-20 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-23 00:00:00'),
 Timestamp('2018-01-25 00:00:00'),
 Timestamp('2018-01-31 00:00:00'),
 Timestamp('2018-02-01 00:00:00'),
 Timestamp('2018-02-05 00:00:00'),
 Timestamp('2018-02-14 00:00:00'),
 Timestamp('2018-03-02 00:00:00'),
 Timestamp('2018-03-07 00:00:00'),
 Timestamp('2018-03-09 00:00:00'),
 Timestamp('2018-03-14 00:00:00'),
 Timestamp('2018-03-20 00:00:00'),
 Timestamp('2018-04-20 00:00:00'),
 Timestamp('2018-05-11 00:00:00'),
 Timestamp('2018-05-16 00:00:00'),
 Timestamp('2018-05-18 00:00:00'),
 Timestamp('2018-05-18 00:00:00'),
 Timestamp('2018-05-25 00:00:00'),
 Timestamp('2018-05-05 00:00:00'),
 Timestamp('2018-05-03 00:00:00'),
 Timestamp('2018-04-22 00:00:00'),
 Timestamp('2018-04-19 00:00:00'),
 Timestamp('2018-04-12 00:00:00'),
 Timestamp('2018-03-16 00:00:00'),
 Timestamp('2018-03-13 00:00:00'),
 Timestamp('2018-03-13 00:00:00'),
 Timestamp('2018-03-05 00:00:00'),
 Timestamp('2018-03-04 00:00:00'),
 Timestamp('2018-02-28 00:00:00'),
 Timestamp('2018-02-27 00:00:00'),
 Timestamp('2018-02-27 00:00:00'),
 Timestamp('2018-02-26 00:00:00'),
 Timestamp('2018-02-24 00:00:00'),
 Timestamp('2018-02-23 00:00:00'),
 Timestamp('2018-02-20 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-08 00:00:00'),
 Timestamp('2018-01-26 00:00:00'),
 Timestamp('2018-01-15 00:00:00'),
 Timestamp('2018-01-04 00:00:00'),
 Timestamp('2017-12-31 00:00:00'),
 Timestamp('2017-12-27 00:00:00'),
 Timestamp('2017-12-19 00:00:00'),
 Timestamp('2017-12-14 00:00:00'),
 Timestamp('2017-12-13 00:00:00'),
 Timestamp('2017-12-12 00:00:00'),
 Timestamp('2017-12-12 00:00:00'),
 Timestamp('2017-12-11 00:00:00'),
 Timestamp('2017-11-30 00:00:00'),
 Timestamp('2017-11-29 00:00:00'),
 Timestamp('2017-11-28 00:00:00'),
 Timestamp('2017-11-23 00:00:00'),
 Timestamp('2017-11-17 00:00:00'),
 Timestamp('2017-11-11 00:00:00'),
 Timestamp('2017-11-10 00:00:00'),
 Timestamp('2017-11-10 00:00:00'),
 Timestamp('2017-11-09 00:00:00'),
 Timestamp('2017-11-07 00:00:00'),
 Timestamp('2017-11-03 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-10-25 00:00:00'),
 Timestamp('2017-10-19 00:00:00'),
 Timestamp('2017-10-14 00:00:00'),
 Timestamp('2017-10-11 00:00:00'),
 Timestamp('2017-10-09 00:00:00'),
 Timestamp('2017-09-30 00:00:00'),
 Timestamp('2017-09-29 00:00:00'),
 Timestamp('2017-09-17 00:00:00'),
 Timestamp('2017-09-12 00:00:00'),
 Timestamp('2017-09-08 00:00:00'),
 Timestamp('2017-09-08 00:00:00'),
 Timestamp('2017-09-05 00:00:00'),
 Timestamp('2017-09-01 00:00:00'),
 Timestamp('2017-08-17 00:00:00'),
 Timestamp('2017-07-23 00:00:00'),
 Timestamp('2017-07-21 00:00:00'),
 Timestamp('2017-07-19 00:00:00'),
 Timestamp('2017-07-13 00:00:00'),
 Timestamp('2017-06-22 00:00:00'),
 Timestamp('2017-06-16 00:00:00'),
 Timestamp('2017-06-05 00:00:00'),
 Timestamp('2017-05-24 00:00:00'),
 Timestamp('2017-05-23 00:00:00'),
 Timestamp('2017-05-15 00:00:00'),
 Timestamp('2017-05-02 00:00:00'),
 Timestamp('2017-04-25 00:00:00'),
 Timestamp('2017-04-15 00:00:00'),
 Timestamp('2017-04-07 00:00:00'),
 Timestamp('2017-03-31 00:00:00'),
 Timestamp('2017-03-15 00:00:00'),
 Timestamp('2017-03-13 00:00:00'),
 Timestamp('2017-02-06 00:00:00'),
 Timestamp('2017-01-27 00:00:00'),
 Timestamp('2017-01-22 00:00:00'),
 Timestamp('2017-01-17 00:00:00'),
 Timestamp('2017-01-10 00:00:00'),
 Timestamp('2017-01-05 00:00:00'),
 Timestamp('2016-12-29 00:00:00'),
 Timestamp('2016-12-09 00:00:00'),
 Timestamp('2016-11-17 00:00:00'),
 Timestamp('2016-11-11 00:00:00'),
 Timestamp('2016-11-03 00:00:00'),
 Timestamp('2016-11-02 00:00:00'),
 Timestamp('2016-10-23 00:00:00'),
 Timestamp('2016-10-23 00:00:00'),
 Timestamp('2016-10-06 00:00:00'),
 Timestamp('2016-09-15 00:00:00'),
 Timestamp('2016-09-08 00:00:00'),
 Timestamp('2016-09-02 00:00:00'),
 Timestamp('2016-08-25 00:00:00'),
 Timestamp('2016-07-25 00:00:00'),
 Timestamp('2016-07-07 00:00:00'),
 Timestamp('2016-06-10 00:00:00'),
 Timestamp('2016-06-07 00:00:00'),
 Timestamp('2016-05-15 00:00:00'),
 Timestamp('2016-05-13 00:00:00'),
 Timestamp('2016-05-11 00:00:00'),
 Timestamp('2016-05-06 00:00:00'),
 Timestamp('2016-05-06 00:00:00'),
 Timestamp('2016-05-06 00:00:00'),
 Timestamp('2016-05-05 00:00:00'),
 Timestamp('2016-05-02 00:00:00'),
 Timestamp('2016-04-29 00:00:00'),
 Timestamp('2016-04-16 00:00:00'),
 Timestamp('2016-04-02 00:00:00'),
 Timestamp('2016-03-27 00:00:00'),
 Timestamp('2016-03-23 00:00:00'),
 Timestamp('2016-03-21 00:00:00'),
 Timestamp('2016-03-15 00:00:00'),
 Timestamp('2016-02-26 00:00:00'),
 Timestamp('2016-02-17 00:00:00'),
 Timestamp('2016-01-20 00:00:00'),
 Timestamp('2016-01-13 00:00:00'),
 Timestamp('2016-01-12 00:00:00'),
 Timestamp('2015-12-29 00:00:00'),
 Timestamp('2015-12-18 00:00:00'),
 Timestamp('2015-11-29 00:00:00'),
 Timestamp('2015-11-11 00:00:00'),
 Timestamp('2015-11-10 00:00:00'),
 Timestamp('2015-11-05 00:00:00'),
 Timestamp('2015-10-25 00:00:00'),
 Timestamp('2015-10-24 00:00:00'),
 Timestamp('2015-10-15 00:00:00'),
 Timestamp('2015-10-15 00:00:00'),
 Timestamp('2015-10-11 00:00:00'),
 Timestamp('2015-10-06 00:00:00'),
 Timestamp('2015-10-02 00:00:00'),
 Timestamp('2015-09-28 00:00:00'),
 Timestamp('2015-09-22 00:00:00'),
 Timestamp('2015-09-11 00:00:00'),
 Timestamp('2015-08-26 00:00:00'),
 Timestamp('2015-08-25 00:00:00'),
 Timestamp('2015-08-23 00:00:00'),
 Timestamp('2015-08-08 00:00:00'),
 Timestamp('2015-08-08 00:00:00'),
 Timestamp('2015-07-27 00:00:00'),
 Timestamp('2015-07-24 00:00:00'),
 Timestamp('2015-07-05 00:00:00'),
 Timestamp('2015-06-23 00:00:00'),
 Timestamp('2015-06-04 00:00:00'),
 Timestamp('2015-05-27 00:00:00'),
 Timestamp('2015-05-20 00:00:00'),
 Timestamp('2015-05-05 00:00:00'),
 Timestamp('2015-05-04 00:00:00'),
 Timestamp('2015-05-04 00:00:00'),
 Timestamp('2015-04-22 00:00:00'),
 Timestamp('2015-04-19 00:00:00'),
 Timestamp('2015-04-18 00:00:00'),
 Timestamp('2015-04-17 00:00:00'),
 Timestamp('2015-04-04 00:00:00'),
 Timestamp('2015-04-02 00:00:00'),
 Timestamp('2015-04-02 00:00:00'),
 Timestamp('2015-02-15 00:00:00'),
 Timestamp('2015-02-15 00:00:00'),
 Timestamp('2015-02-15 00:00:00'),
 Timestamp('2015-02-05 00:00:00'),
 Timestamp('2015-02-02 00:00:00'),
 Timestamp('2015-01-26 00:00:00'),
 Timestamp('2015-01-23 00:00:00'),
 Timestamp('2014-12-17 00:00:00'),
 Timestamp('2014-12-17 00:00:00'),
 Timestamp('2014-11-23 00:00:00'),
 Timestamp('2014-10-21 00:00:00'),
 Timestamp('2014-10-18 00:00:00'),
 Timestamp('2014-10-13 00:00:00'),
 Timestamp('2014-10-08 00:00:00'),
 Timestamp('2014-09-10 00:00:00'),
 Timestamp('2014-09-05 00:00:00'),
 Timestamp('2014-09-02 00:00:00'),
 Timestamp('2014-08-14 00:00:00'),
 Timestamp('2014-08-13 00:00:00'),
 Timestamp('2014-06-27 00:00:00'),
 Timestamp('2014-06-23 00:00:00'),
 Timestamp('2014-05-21 00:00:00'),
 Timestamp('2014-05-03 00:00:00'),
 Timestamp('2014-05-02 00:00:00'),
 Timestamp('2014-04-21 00:00:00'),
 Timestamp('2014-04-21 00:00:00'),
 Timestamp('2014-04-16 00:00:00'),
 Timestamp('2014-04-03 00:00:00'),
 Timestamp('2014-03-30 00:00:00'),
 Timestamp('2014-03-23 00:00:00'),
 Timestamp('2014-03-08 00:00:00'),
 Timestamp('2014-03-07 00:00:00'),
 Timestamp('2014-03-02 00:00:00'),
 Timestamp('2014-02-20 00:00:00'),
 Timestamp('2014-02-07 00:00:00'),
 Timestamp('2014-01-15 00:00:00'),
 Timestamp('2013-11-21 00:00:00'),
 Timestamp('2013-11-01 00:00:00'),
 Timestamp('2013-10-15 00:00:00'),
 Timestamp('2013-09-28 00:00:00'),
 Timestamp('2013-09-21 00:00:00'),
 Timestamp('2013-08-22 00:00:00'),
 Timestamp('2013-08-15 00:00:00'),
 Timestamp('2013-06-19 00:00:00'),
 Timestamp('2013-05-03 00:00:00'),
 Timestamp('2013-04-29 00:00:00'),
 Timestamp('2013-04-15 00:00:00'),
 Timestamp('2013-04-13 00:00:00'),
 Timestamp('2013-03-21 00:00:00'),
 Timestamp('2013-02-27 00:00:00'),
 Timestamp('2013-02-13 00:00:00'),
 Timestamp('2013-02-01 00:00:00'),
 Timestamp('2013-01-08 00:00:00')]

In [1]:
def todict():
    import pandas as pd
    df = pd.read_csv("school_shooting.csv")
    df['Date'] = pd.to_datetime(df['Date'])
    column_names = list(df.columns)
    final_list = []
    name_list = []
    for item in column_names:
        name_list.append(item)
        final_list.append([i for i in df[item]])
        
    dictionary = dict(zip(name_list, final_list))
    
    return dictionary

In [2]:
todict()

{'Date': [Timestamp('2013-01-07 00:00:00'),
  Timestamp('2013-01-10 00:00:00'),
  Timestamp('2013-01-12 00:00:00'),
  Timestamp('2013-01-15 00:00:00'),
  Timestamp('2013-01-15 00:00:00'),
  Timestamp('2013-01-16 00:00:00'),
  Timestamp('2013-01-22 00:00:00'),
  Timestamp('2013-01-31 00:00:00'),
  Timestamp('2013-01-31 00:00:00'),
  Timestamp('2013-03-18 00:00:00'),
  Timestamp('2013-04-12 00:00:00'),
  Timestamp('2013-04-16 00:00:00'),
  Timestamp('2013-04-18 00:00:00'),
  Timestamp('2013-05-14 00:00:00'),
  Timestamp('2013-06-07 00:00:00'),
  Timestamp('2013-08-20 00:00:00'),
  Timestamp('2013-08-23 00:00:00'),
  Timestamp('2013-08-30 00:00:00'),
  Timestamp('2013-10-04 00:00:00'),
  Timestamp('2013-10-21 00:00:00'),
  Timestamp('2013-11-02 00:00:00'),
  Timestamp('2013-11-03 00:00:00'),
  Timestamp('2013-11-13 00:00:00'),
  Timestamp('2013-12-04 00:00:00'),
  Timestamp('2013-12-13 00:00:00'),
  Timestamp('2013-12-19 00:00:00'),
  Timestamp('2014-01-09 00:00:00'),
  Timestamp('2014-01-13 00:00:00'),
  Timestamp('2014-01-14 00:00:00'),
  Timestamp('2014-01-17 00:00:00'),
  Timestamp('2014-01-20 00:00:00'),
  Timestamp('2014-01-21 00:00:00'),
  Timestamp('2014-01-24 00:00:00'),
  Timestamp('2014-01-25 00:00:00'),
  Timestamp('2014-01-27 00:00:00'),
  Timestamp('2014-01-28 00:00:00'),
  Timestamp('2014-01-28 00:00:00'),
  Timestamp('2014-01-30 00:00:00'),
  Timestamp('2014-01-31 00:00:00'),
  Timestamp('2014-01-31 00:00:00'),
  Timestamp('2014-02-10 00:00:00'),
  Timestamp('2014-02-10 00:00:00'),
  Timestamp('2014-02-12 00:00:00'),
  Timestamp('2014-02-22 00:00:00'),
  Timestamp('2014-03-12 00:00:00'),
  Timestamp('2014-04-09 00:00:00'),
  Timestamp('2014-04-11 00:00:00'),
  Timestamp('2014-05-04 00:00:00'),
  Timestamp('2014-05-08 00:00:00'),
  Timestamp('2014-05-08 00:00:00'),
  Timestamp('2014-05-14 00:00:00'),
  Timestamp('2014-06-05 00:00:00'),
  Timestamp('2014-06-10 00:00:00'),
  Timestamp('2014-09-09 00:00:00'),
  Timestamp('2014-09-11 00:00:00'),
  Timestamp('2014-09-27 00:00:00'),
  Timestamp('2014-09-30 00:00:00'),
  Timestamp('2014-09-30 00:00:00'),
  Timestamp('2014-10-03 00:00:00'),
  Timestamp('2014-10-24 00:00:00'),
  Timestamp('2014-11-20 00:00:00'),
  Timestamp('2014-11-20 00:00:00'),
  Timestamp('2014-12-05 00:00:00'),
  Timestamp('2014-12-12 00:00:00'),
  Timestamp('2015-01-15 00:00:00'),
  Timestamp('2015-01-16 00:00:00'),
  Timestamp('2015-02-04 00:00:00'),
  Timestamp('2015-02-14 00:00:00'),
  Timestamp('2015-02-23 00:00:00'),
  Timestamp('2015-03-30 00:00:00'),
  Timestamp('2015-04-13 00:00:00'),
  Timestamp('2015-04-16 00:00:00'),
  Timestamp('2015-04-27 00:00:00'),
  Timestamp('2015-05-12 00:00:00'),
  Timestamp('2015-05-24 00:00:00'),
  Timestamp('2015-08-27 00:00:00'),
  Timestamp('2015-09-03 00:00:00'),
  Timestamp('2015-09-14 00:00:00'),
  Timestamp('2015-09-30 00:00:00'),
  Timestamp('2015-10-01 00:00:00'),
  Timestamp('2015-10-09 00:00:00'),
  Timestamp('2015-10-09 00:00:00'),
  Timestamp('2015-10-22 00:00:00'),
  Timestamp('2015-11-01 00:00:00'),
  Timestamp('2015-11-20 00:00:00'),
  Timestamp('2016-01-22 00:00:00'),
  Timestamp('2016-01-29 00:00:00'),
  Timestamp('2016-02-09 00:00:00'),
  Timestamp('2016-02-12 00:00:00'),
  Timestamp('2016-02-29 00:00:00'),
  Timestamp('2016-04-23 00:00:00'),
  Timestamp('2016-06-01 00:00:00'),
  Timestamp('2016-06-08 00:00:00'),
  Timestamp('2016-09-09 00:00:00'),
  Timestamp('2016-09-28 00:00:00'),
  Timestamp('2016-10-11 00:00:00'),
  Timestamp('2016-10-13 00:00:00'),
  Timestamp('2016-10-18 00:00:00'),
  Timestamp('2016-10-25 00:00:00'),
  Timestamp('2016-12-01 00:00:00'),
  Timestamp('2017-01-20 00:00:00'),
  Timestamp('2017-01-20 00:00:00'),
  Timestamp('2017-03-21 00:00:00'),
  Timestamp('2017-04-10 00:00:00'),
  Timestamp('2017-05-04 00:00:00'),
  Timestamp('2017-09-13 00:00:00'),
  Timestamp('2017-09-20 00:00:00'),
  Timestamp('2017-11-14 00:00:00'),
  Timestamp('2017-12-07 00:00:00'),
  Timestamp('2018-01-10 00:00:00'),
  Timestamp('2018-01-20 00:00:00'),
  Timestamp('2018-01-22 00:00:00'),
  Timestamp('2018-01-22 00:00:00'),
  Timestamp('2018-01-23 00:00:00'),
  Timestamp('2018-01-25 00:00:00'),
  Timestamp('2018-01-31 00:00:00'),
  Timestamp('2018-02-01 00:00:00'),
  Timestamp('2018-02-05 00:00:00'),
  Timestamp('2018-02-14 00:00:00'),
  Timestamp('2018-03-02 00:00:00'),
  Timestamp('2018-03-07 00:00:00'),
  Timestamp('2018-03-09 00:00:00'),
  Timestamp('2018-03-14 00:00:00'),
  Timestamp('2018-03-20 00:00:00'),
  Timestamp('2018-04-20 00:00:00'),
  Timestamp('2018-05-11 00:00:00'),
  Timestamp('2018-05-16 00:00:00'),
  Timestamp('2018-05-18 00:00:00'),
  Timestamp('2018-05-18 00:00:00'),
  Timestamp('2018-05-25 00:00:00'),
  Timestamp('2018-05-05 00:00:00'),
  Timestamp('2018-05-03 00:00:00'),
  Timestamp('2018-04-22 00:00:00'),
  Timestamp('2018-04-19 00:00:00'),
  Timestamp('2018-04-12 00:00:00'),
  Timestamp('2018-03-16 00:00:00'),
  Timestamp('2018-03-13 00:00:00'),
  Timestamp('2018-03-13 00:00:00'),
  Timestamp('2018-03-05 00:00:00'),
  Timestamp('2018-03-04 00:00:00'),
  Timestamp('2018-02-28 00:00:00'),
  Timestamp('2018-02-27 00:00:00'),
  Timestamp('2018-02-27 00:00:00'),
  Timestamp('2018-02-26 00:00:00'),
  Timestamp('2018-02-24 00:00:00'),
  Timestamp('2018-02-23 00:00:00'),
  Timestamp('2018-02-20 00:00:00'),
  Timestamp('2018-02-15 00:00:00'),
  Timestamp('2018-02-08 00:00:00'),
  Timestamp('2018-01-26 00:00:00'),
  Timestamp('2018-01-15 00:00:00'),
  Timestamp('2018-01-04 00:00:00'),
  Timestamp('2017-12-31 00:00:00'),
  Timestamp('2017-12-27 00:00:00'),
  Timestamp('2017-12-19 00:00:00'),
  Timestamp('2017-12-14 00:00:00'),
  Timestamp('2017-12-13 00:00:00'),
  Timestamp('2017-12-12 00:00:00'),
  Timestamp('2017-12-12 00:00:00'),
  Timestamp('2017-12-11 00:00:00'),
  Timestamp('2017-11-30 00:00:00'),
  Timestamp('2017-11-29 00:00:00'),
  Timestamp('2017-11-28 00:00:00'),
  Timestamp('2017-11-23 00:00:00'),
  Timestamp('2017-11-17 00:00:00'),
  Timestamp('2017-11-11 00:00:00'),
  Timestamp('2017-11-10 00:00:00'),
  Timestamp('2017-11-10 00:00:00'),
  Timestamp('2017-11-09 00:00:00'),
  Timestamp('2017-11-07 00:00:00'),
  Timestamp('2017-11-03 00:00:00'),
  Timestamp('2017-10-31 00:00:00'),
  Timestamp('2017-10-25 00:00:00'),
  Timestamp('2017-10-19 00:00:00'),
  Timestamp('2017-10-14 00:00:00'),
  Timestamp('2017-10-11 00:00:00'),
  Timestamp('2017-10-09 00:00:00'),
  Timestamp('2017-09-30 00:00:00'),
  Timestamp('2017-09-29 00:00:00'),
  Timestamp('2017-09-17 00:00:00'),
  Timestamp('2017-09-12 00:00:00'),
  Timestamp('2017-09-08 00:00:00'),
  Timestamp('2017-09-08 00:00:00'),
  Timestamp('2017-09-05 00:00:00'),
  Timestamp('2017-09-01 00:00:00'),
  Timestamp('2017-08-17 00:00:00'),
  Timestamp('2017-07-23 00:00:00'),
  Timestamp('2017-07-21 00:00:00'),
  Timestamp('2017-07-19 00:00:00'),
  Timestamp('2017-07-13 00:00:00'),
  Timestamp('2017-06-22 00:00:00'),
  Timestamp('2017-06-16 00:00:00'),
  Timestamp('2017-06-05 00:00:00'),
  Timestamp('2017-05-24 00:00:00'),
  Timestamp('2017-05-23 00:00:00'),
  Timestamp('2017-05-15 00:00:00'),
  Timestamp('2017-05-02 00:00:00'),
  Timestamp('2017-04-25 00:00:00'),
  Timestamp('2017-04-15 00:00:00'),
  Timestamp('2017-04-07 00:00:00'),
  Timestamp('2017-03-31 00:00:00'),
  Timestamp('2017-03-15 00:00:00'),
  Timestamp('2017-03-13 00:00:00'),
  Timestamp('2017-02-06 00:00:00'),
  Timestamp('2017-01-27 00:00:00'),
  Timestamp('2017-01-22 00:00:00'),
  Timestamp('2017-01-17 00:00:00'),
  Timestamp('2017-01-10 00:00:00'),
  Timestamp('2017-01-05 00:00:00'),
  Timestamp('2016-12-29 00:00:00'),
  Timestamp('2016-12-09 00:00:00'),
  Timestamp('2016-11-17 00:00:00'),
  Timestamp('2016-11-11 00:00:00'),
  Timestamp('2016-11-03 00:00:00'),
  Timestamp('2016-11-02 00:00:00'),
  Timestamp('2016-10-23 00:00:00'),
  Timestamp('2016-10-23 00:00:00'),
  Timestamp('2016-10-06 00:00:00'),
  Timestamp('2016-09-15 00:00:00'),
  Timestamp('2016-09-08 00:00:00'),
  Timestamp('2016-09-02 00:00:00'),
  Timestamp('2016-08-25 00:00:00'),
  Timestamp('2016-07-25 00:00:00'),
  Timestamp('2016-07-07 00:00:00'),
  Timestamp('2016-06-10 00:00:00'),
  Timestamp('2016-06-07 00:00:00'),
  Timestamp('2016-05-15 00:00:00'),
  Timestamp('2016-05-13 00:00:00'),
  Timestamp('2016-05-11 00:00:00'),
  Timestamp('2016-05-06 00:00:00'),
  Timestamp('2016-05-06 00:00:00'),
  Timestamp('2016-05-06 00:00:00'),
  Timestamp('2016-05-05 00:00:00'),
  Timestamp('2016-05-02 00:00:00'),
  Timestamp('2016-04-29 00:00:00'),
  Timestamp('2016-04-16 00:00:00'),
  Timestamp('2016-04-02 00:00:00'),
  Timestamp('2016-03-27 00:00:00'),
  Timestamp('2016-03-23 00:00:00'),
  Timestamp('2016-03-21 00:00:00'),
  Timestamp('2016-03-15 00:00:00'),
  Timestamp('2016-02-26 00:00:00'),
  Timestamp('2016-02-17 00:00:00'),
  Timestamp('2016-01-20 00:00:00'),
  Timestamp('2016-01-13 00:00:00'),
  Timestamp('2016-01-12 00:00:00'),
  Timestamp('2015-12-29 00:00:00'),
  Timestamp('2015-12-18 00:00:00'),
  Timestamp('2015-11-29 00:00:00'),
  Timestamp('2015-11-11 00:00:00'),
  Timestamp('2015-11-10 00:00:00'),
  Timestamp('2015-11-05 00:00:00'),
  Timestamp('2015-10-25 00:00:00'),
  Timestamp('2015-10-24 00:00:00'),
  Timestamp('2015-10-15 00:00:00'),
  Timestamp('2015-10-15 00:00:00'),
  Timestamp('2015-10-11 00:00:00'),
  Timestamp('2015-10-06 00:00:00'),
  Timestamp('2015-10-02 00:00:00'),
  Timestamp('2015-09-28 00:00:00'),
  Timestamp('2015-09-22 00:00:00'),
  Timestamp('2015-09-11 00:00:00'),
  Timestamp('2015-08-26 00:00:00'),
  Timestamp('2015-08-25 00:00:00'),
  Timestamp('2015-08-23 00:00:00'),
  Timestamp('2015-08-08 00:00:00'),
  Timestamp('2015-08-08 00:00:00'),
  Timestamp('2015-07-27 00:00:00'),
  Timestamp('2015-07-24 00:00:00'),
  Timestamp('2015-07-05 00:00:00'),
  Timestamp('2015-06-23 00:00:00'),
  Timestamp('2015-06-04 00:00:00'),
  Timestamp('2015-05-27 00:00:00'),
  Timestamp('2015-05-20 00:00:00'),
  Timestamp('2015-05-05 00:00:00'),
  Timestamp('2015-05-04 00:00:00'),
  Timestamp('2015-05-04 00:00:00'),
  Timestamp('2015-04-22 00:00:00'),
  Timestamp('2015-04-19 00:00:00'),
  Timestamp('2015-04-18 00:00:00'),
  Timestamp('2015-04-17 00:00:00'),
  Timestamp('2015-04-04 00:00:00'),
  Timestamp('2015-04-02 00:00:00'),
  Timestamp('2015-04-02 00:00:00'),
  Timestamp('2015-02-15 00:00:00'),
  Timestamp('2015-02-15 00:00:00'),
  Timestamp('2015-02-15 00:00:00'),
  Timestamp('2015-02-05 00:00:00'),
  Timestamp('2015-02-02 00:00:00'),
  Timestamp('2015-01-26 00:00:00'),
  Timestamp('2015-01-23 00:00:00'),
  Timestamp('2014-12-17 00:00:00'),
  Timestamp('2014-12-17 00:00:00'),
  Timestamp('2014-11-23 00:00:00'),
  Timestamp('2014-10-21 00:00:00'),
  Timestamp('2014-10-18 00:00:00'),
  Timestamp('2014-10-13 00:00:00'),
  Timestamp('2014-10-08 00:00:00'),
  Timestamp('2014-09-10 00:00:00'),
  Timestamp('2014-09-05 00:00:00'),
  Timestamp('2014-09-02 00:00:00'),
  Timestamp('2014-08-14 00:00:00'),
  Timestamp('2014-08-13 00:00:00'),
  Timestamp('2014-06-27 00:00:00'),
  Timestamp('2014-06-23 00:00:00'),
  Timestamp('2014-05-21 00:00:00'),
  Timestamp('2014-05-03 00:00:00'),
  Timestamp('2014-05-02 00:00:00'),
  Timestamp('2014-04-21 00:00:00'),
  Timestamp('2014-04-21 00:00:00'),
  Timestamp('2014-04-16 00:00:00'),
  Timestamp('2014-04-03 00:00:00'),
  Timestamp('2014-03-30 00:00:00'),
  Timestamp('2014-03-23 00:00:00'),
  Timestamp('2014-03-08 00:00:00'),
  Timestamp('2014-03-07 00:00:00'),
  Timestamp('2014-03-02 00:00:00'),
  Timestamp('2014-02-20 00:00:00'),
  Timestamp('2014-02-07 00:00:00'),
  Timestamp('2014-01-15 00:00:00'),
  Timestamp('2013-11-21 00:00:00'),
  Timestamp('2013-11-01 00:00:00'),
  Timestamp('2013-10-15 00:00:00'),
  Timestamp('2013-09-28 00:00:00'),
  Timestamp('2013-09-21 00:00:00'),
  Timestamp('2013-08-22 00:00:00'),
  Timestamp('2013-08-15 00:00:00'),
  Timestamp('2013-06-19 00:00:00'),
  Timestamp('2013-05-03 00:00:00'),
  Timestamp('2013-04-29 00:00:00'),
  Timestamp('2013-04-15 00:00:00'),
  Timestamp('2013-04-13 00:00:00'),
  Timestamp('2013-03-21 00:00:00'),
  Timestamp('2013-02-27 00:00:00'),
  Timestamp('2013-02-13 00:00:00'),
  Timestamp('2013-02-01 00:00:00'),
  Timestamp('2013-01-08 00:00:00')],
 'Death': [1.0,
  0.0,
  0.0,
  0.0,
  3.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  6.0,
  0.0,
  1.0,
  0.0,
  0.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  5.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  2.0,
  0.0,
  10.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  2.0,
  0.0,
  1.0,
  2.0,
  1.0,
  1.0,
  2.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  3.0,
  2.0,
  1.0,
  0.0,
  6.0,
  3.0,
  0.0,
  1.0,
  0.0,
  0.0,
  2.0,
  0.0,
  1.0,
  0.0,
  0.0,
  17.0,
  2.0,
  1.0,
  0.0,
  2.0,
  2.0,
  0.0,
  0.0,
  0.0,
  10.0,
  1.0,
  0.0,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'Injuries': [0.0,
  2.0,
  1.0,
  2.0,
  0.0,
  0.0,
  3.0,
  0.0,
  2.0,
  0.0,
  2.0,
  3.0,
  0.0,
  0.0,
  4.0,
  0.0,
  2.0,
  1.0,
  2.0,
  2.0,
  1.0,
  2.0,
  3.0,
  1.0,
  0.0,
  1.0,
  1.0,
  1.0,
  3.0,
  2.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  1.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  3.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  1.0,
  3.0,
  1.0,
  0.0,
  4.0,
  3.0,
  2.0,
  2.0,
  0.0,
  3.0,
  1.0,
  0.0,
  1.0,
  0.0,
  2.0,
  7.0,
  0.0,
  2.0,
  0.0,
  1.0,
  9.0,
  3.0,
  1.0,
  3.0,
  1.0,
  0.0,
  1.0,
  0.0,
  4.0,
  0.0,
  4.0,
  2.0,
  0.0,
  3.0,
  2.0,
  2.0,
  1.0,
  2.0,
  4.0,
  1.0,
  0.0,
  1.0,
  1.0,
  1.0,
  1.0,
  0.0,
  3.0,
  1.0,
  18.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  18.0,
  0.0,
  0.0,
  5.0,
  1.0,
  17.0,
  0.0,
  2.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  14.0,
  3.0,
  2.0,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'Latitude': [26.640628000000003,
  50.9954169,
  42.3486635,
  38.62727329999999,
  37.24954,
  41.8755546,
  29.7589382,
  33.448586600000006,
  33.749098700000005,
  28.5423999,
  37.1298517,
  33.2668398,
  42.3750997,
  33.5206824,
  46.724362,
  33.7737582,
  31.8009956,
  36.0998131,
  28.5825505,
  39.5348431,
  36.0726355,
  33.806216600000006,
  40.4416941,
  28.5502685,
  39.5680644,
  36.7295295,
  35.6144446,
  41.3082138,
  33.394328200000004,
  39.9524152,
  39.849557,
  40.4258686,
  33.4918203,
  34.054935,
  37.7274692,
  36.1622296,
  32.527650300000005,
  28.0331886,
  33.448586600000006,
  41.5910641,
  -28.7464779,
  41.520052,
  34.054935,
  33.470971399999996,
  25.7742658,
  35.612660999999996,
  42.3486635,
  33.470971399999996,
  19.2953549,
  33.9562149,
  49.1632727,
  47.6038321,
  45.5317928,
  25.7742658,
  40.667751700000004,
  39.466702500000004,
  35.60846655,
  38.254237599999996,
  33.5670562,
  48.0517429,
  29.9812352,
  25.7742658,
  36.312589700000004,
  45.5202471,
  43.0349931,
  29.187198600000002,
  39.4142186,
  37.3029568,
  29.2108147,
  38.6558849,
  35.3848841,
  50.2472968,
  47.0263876,
  33.4144139,
  43.0171773,
  32.0835407,
  38.5815719,
  33.7440023,
  43.431366,
  43.216505,
  35.199458,
  29.7589382,
  36.1622296,
  36.0998131,
  36.2008371,
  39.7683331,
  39.9524152,
  43.201126,
  33.558997,
  39.5150576,
  45.140245,
  34.054935,
  42.297320500000005,
  30.357380199999998,
  34.56371370000001,
  30.738799800000002,
  39.9622601,
  45.4423543,
  40.572851,
  40.889461100000005,
  40.2522771,
  40.2522771,
  43.929319,
  34.1083449,
  32.829518300000004,
  47.4521207,
  39.4842821,
  49.957280700000005,
  36.8220629,
  33.7556593,
  36.0998131,
  32.1840381,
  30.03280175,
  36.8572781,
  30.6943566,
  39.9524152,
  34.054935,
  38.8035961,
  26.3100794,
  43.597646000000005,
  33.5206824,
  38.0464066,
  33.5206824,
  38.2367924,
  29.187198600000002,
  34.5793131,
  41.842224,
  33.7236409,
  33.521501300000004,
  40.0455918,
  42.6605894,
  35.319836200000005,
  33.749098700000005,
  32.29903839999999,
  39.0086171,
  46.8700801,
  49.27187070000001,
  38.8147596,
  37.9875505,
  29.882643599999998,
  34.769186700000006,
  36.846292299999995,
  33.49512,
  47.24957979999999,
  32.0835407,
  41.5833658,
  40.7967244,
  26.271462800000002,
  40.7306458,
  42.3222599,
  32.5447756,
  47.6038321,
  48.0517429,
  45.1412642,
  43.089993,
  32.7762719,
  40.6872885,
  41.003646200000006,
  29.6910625,
  35.9556924,
  36.8529841,
  40.742551,
  37.3297085,
  39.739142799999996,
  35.6144446,
  31.578206199999997,
  33.0801429,
  33.425125,
  34.0580391,
  32.753177,
  42.73377120000001,
  40.7670126,
  32.527650300000005,
  37.1924594,
  37.1924594,
  42.0245442,
  33.5778631,
  40.713120700000005,
  38.9107156,
  41.083064,
  44.9504037,
  39.9622601,
  34.745627500000005,
  36.1622296,
  30.6253463,
  33.7939953,
  36.0625843,
  40.114955,
  43.0349931,
  36.1662859,
  34.1954,
  41.8755546,
  41.0799898,
  32.7045753,
  30.6604815,
  30.3027042,
  32.829518300000004,
  40.2971825,
  36.1556805,

In [12]:
from pymongo import MongoClient

In [13]:
def Add_to_DB(record):
    # Making a Connection with MongoClient 
    client = MongoClient()
    # select/create database
    db = client.SchoolShoot_db
    # select/create collection
    collection = db.Shooter
    # insert record into collection as a document
    post = collection.insert_one(record)

In [14]:
dictt = todict()
Add_to_DB(dictt)

In [10]:
import pymongo
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)
db = client.SchoolShoot_db
SS = db.SchoolShoot_db

In [11]:
School_sh = SS.find()
for ss in School_sh:
    print(ss)